### ISSUE TITLE
NeDB services generate and use /data folder instead of /server/data.

### ISSUE THREAD

**Issue by gustojs** [leopiccionia/nuxt-feathers-boilerplate#2]
NeDB database uses JSON files to store data directly in the filesystem. By default it happens inside of the Feathers folder in `/data`, but since we generate the services from the parent level directory, `/data` gets created among other Nuxt folders instead of `/server/data`.

**Comment by leopiccionia** [comment]
This should be fixed in 7c73dc2.

Feel free to suggest a different approach in another issue.
