### ISSUE TITLE
What happened with the logger?

### ISSUE THREAD

**Issue by gustojs** [leopiccionia/nuxt-feathers-boilerplate#4]
By default, Feathers CLI generates a `./logger.js` file which is missing here. I don't mind it missing personally, but some services generated with `feathers generate service` (f.e. for MongoDB) take the existence of this file for granted and try to import it.

Was there some specific reason for removing it?

**Comment by leopiccionia** [comment]
No critical reason. I've just been using Consola (that comes with Nuxt) for my own use, and I've never used Feathers with Mongo before, so I wasn't aware of this issue.

I've re-created `./logger.js` in 2072e2390ea691714617f58734c18131e9d18e51, now using Consola isntead of Winston. It seems to work nicely, according to my tests. Please let me know if you still find related issues.
